# Generated by Django 4.1.1 on 2022-11-03 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_phoneNumber_verified',
            field=models.BooleanField(default=False),
        ),
    ]
